routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/clear', function(){
    \Illuminate\Support\Facades\Artisan::call('optimize:clear');
});

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/


Route::namespace('Gateway')->prefix('ipn')->name('ipn.')->group(function () {
    Route::post('paypal', 'paypal\ProcessController@ipn')->name('paypal');
    Route::get('paypal_sdk', 'paypal_sdk\ProcessController@ipn')->name('paypal_sdk');
    Route::post('perfect_money', 'perfect_money\ProcessController@ipn')->name('perfect_money');
    Route::post('stripe', 'stripe\ProcessController@ipn')->name('stripe');
    Route::post('stripe_js', 'stripe_js\ProcessController@ipn')->name('stripe_js');
    Route::post('stripe_v3', 'stripe_v3\ProcessController@ipn')->name('stripe_v3');
    Route::post('skrill', 'skrill\ProcessController@ipn')->name('skrill');
    Route::post('paytm', 'paytm\ProcessController@ipn')->name('paytm');
    Route::post('payeer', 'payeer\ProcessController@ipn')->name('payeer');
    Route::post('paystack', 'paystack\ProcessController@ipn')->name('paystack');
    Route::post('voguepay', 'voguepay\ProcessController@ipn')->name('voguepay');
    Route::get('flutterwave/{trx}/{type}', 'flutterwave\ProcessController@ipn')->name('flutterwave');
    Route::post('razorpay', 'razorpay\ProcessController@ipn')->name('razorpay');
    Route::post('instamojo', 'instamojo\ProcessController@ipn')->name('instamojo');
    Route::get('blockchain', 'blockchain\ProcessController@ipn')->name('blockchain');
    Route::get('blockio', 'blockio\ProcessController@ipn')->name('blockio');
    Route::post('coinpayments', 'coinpayments\ProcessController@ipn')->name('coinpayments');
    Route::post('coinpayments_fiat', 'coinpayments_fiat\ProcessController@ipn')->name('coinpayments_fiat');
    Route::post('coingate', 'coingate\ProcessController@ipn')->name('coingate');
    Route::post('coinbase_commerce', 'coinbase_commerce\ProcessController@ipn')->name('coinbase_commerce');
    Route::get('mollie', 'mollie\ProcessController@ipn')->name('mollie');
    Route::post('cashmaal', 'cashmaal\ProcessController@ipn')->name('cashmaal');
});

// User Support Ticket
Route::prefix('ticket')->group(function () {
    Route::get('/', 'TicketController@supportTicket')->name('ticket');
    Route::get('/new', 'TicketController@openSupportTicket')->name('ticket.open');
    Route::post('/create', 'TicketController@storeSupportTicket')->name('ticket.store');
    Route::get('/view/{ticket}', 'TicketController@viewTicket')->name('ticket.view');
    Route::get('/user-view/{ticket}', 'TicketController@viewUserTicket')->name('ticket.view.user');
    Route::post('/reply/{ticket}', 'TicketController@replyTicket')->name('ticket.reply');
    Route::get('/download/{ticket}', 'TicketController@ticketDownload')->name('ticket.download');
});

// User Support Ticket
Route::prefix('ticket')->group(function () {
    Route::get('surveyor/ticket/', 'SurveyorTicketController@supportTicket')->name('surveyor.ticket');
    Route::get('surveyor/ticket/new', 'SurveyorTicketController@openSupportTicket')->name('surveyor.ticket.open');
    Route::post('surveyor/ticket/create', 'SurveyorTicketController@storeSupportTicket')->name('surveyor.ticket.store');
    Route::get('surveyor/ticket/view/{ticket}', 'SurveyorTicketController@viewTicket')->name('surveyor.ticket.view');
    Route::post('surveyor/ticket/reply/{ticket}', 'SurveyorTicketController@replyTicket')->name('surveyor.ticket.reply');
    Route::get('surveyor/ticket/download/{ticket}', 'SurveyorTicketController@ticketDownload')->name('surveyor.ticket.download');
});


/*
|--------------------------------------------------------------------------
| Start Admin Area
|--------------------------------------------------------------------------
*/

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {
    Route::namespace('Auth')->group(function () {
        Route::get('/', 'LoginController@showLoginForm')->name('login');
        Route::post('/', 'LoginController@login')->name('login');
        Route::get('logout', 'LoginController@logout')->name('logout');

        // Admin Password Reset
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.reset');
        Route::post('password/reset', 'ForgotPasswordController@sendResetLinkEmail');
        Route::post('password/verify-code', 'ForgotPasswordController@verifyCode')->name('password.verify-code');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.change-link');
        Route::post('password/reset/change', 'ResetPasswordController@reset')->name('password.change');
    });

    Route::middleware(['admin','access'])->group(function () {
        Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
        Route::get('profile', 'AdminController@profile')->name('profile');
        Route::post('profile', 'AdminController@profileUpdate')->name('profile.update');
        Route::get('password', 'AdminController@password')->name('password');
        Route::post('password', 'AdminController@passwordUpdate')->name('password.update');

        //Manage Category
        Route::get('category', 'CategoryController@categories')->name('category');
        Route::post('category/new', 'CategoryController@storeCategory')->name('category.store');
        Route::get('category-user', 'CategoryController@categoriesUser')->name('categoryUser');
        Route::post('category-user/new', 'CategoryController@storeCategoryUser')->name('categoryUser.store');
        Route::post('category/update/{id}', 'CategoryController@updateCategory')->name('category.update');
        Route::post('category-user/update/{id}', 'CategoryController@updateCategoryUser')->name('categoryUser.update');
        Route::get('category/search', 'CategoryController@searchCategory')->name('category.search');
        Route::get('category-user/search', 'CategoryController@searchCategoryUser')->name('categoryUser.search');
        Route::post('category/activate', 'CategoryController@activate')->name('category.activate');
        Route::post('category/deactivate', 'CategoryController@deactivate')->name('category.deactivate');
        Route::post('category-user/activate', 'CategoryController@activateUser')->name('categoryUser.activate');
        Route::post('category-user/deactivate', 'CategoryController@deactivateUser')->name('categoryUser.deactivate');

        // Users Manager
        Route::get('users', 'ManageUsersController@allUsers')->name('users.all');
        Route::get('users/active', 'ManageUsersController@activeUsers')->name('users.active');
        Route::get('users/banned', 'ManageUsersController@bannedUsers')->name('users.banned');
        Route::get('users/email-verified', 'ManageUsersController@emailVerifiedUsers')->name('users.emailVerified');
        Route::get('users/email-unverified', 'ManageUsersController@emailUnverifiedUsers')->name('users.emailUnverified');
        Route::get('users/sms-unverified', 'ManageUsersController@smsUnverifiedUsers')->name('users.smsUnverified');
        Route::get('users/sms-verified', 'ManageUsersController@smsVerifiedUsers')->name('users.smsVerified');

        Route::get('users/{scope}/search', 'ManageUsersController@search')->name('users.search');
        Route::get('user/detail/{id}', 'ManageUsersController@detail')->name('users.detail');
        Route::post('user/update/{id}', 'ManageUsersController@update')->name('users.update');
        Route::delete('user/delete/{id}', 'ManageUsersController@delete')->name('users.destroy');
        Route::post('user/add-sub-balance/{id}', 'ManageUsersController@addSubBalance')->name('users.addSubBalance');
        Route::get('user/send-email/{id}', 'ManageUsersController@showEmailSingleForm')->name('users.email.single');
        Route::post('user/send-email/{id}', 'ManageUsersController@sendEmailSingle')->name('users.email.single');
        Route::get('user/transactions/{id}', 'ManageUsersController@transactions')->name('users.transactions');
        Route::get('user/deposits/via/{method}/{type?}/{userId}', 'ManageUsersController@depViaMethod')->name('users.deposits.method');
        Route::get('user/withdrawals/{id}', 'ManageUsersController@withdrawals')->name('users.withdrawals');
        Route::get('user/withdrawals/via/{method}/{type?}/{userId}', 'ManageUsersController@withdrawalsViaMethod')->name('users.withdrawals.method');

        // Surveyors Manager
        Route::get('surveyors', 'ManageSurveyorsController@allSurveyors')->name('surveyors.all');
        Route::get('surveyors/active', 'ManageSurveyorsController@activeSurveyors')->name('surveyors.active');
        Route::get('surveyors/banned', 'ManageSurveyorsController@bannedSurveyors')->name('surveyors.banned');
        Route::get('surveyors/email-verified', 'ManageSurveyorsController@emailVerifiedSurveyors')->name('surveyors.emailVerified');
        Route::get('surveyors/email-unverified', 'ManageSurveyorsController@emailUnverifiedSurveyors')->name('surveyors.emailUnverified');
        Route::get('surveyors/sms-unverified', 'ManageSurveyorsController@smsUnverifiedSurveyors')->name('surveyors.smsUnverified');
        Route::get('surveyors/sms-verified', 'ManageSurveyorsController@smsVerifiedSurveyors')->name('surveyors.smsVerified');

        Route::get('surveyors/{scope}/search', 'ManageSurveyorsController@search')->name('surveyors.search');
        Route::get('surveyor/detail/{id}', 'ManageSurveyorsController@detail')->name('surveyors.detail');
        Route::post('surveyor/update/{id}', 'ManageSurveyorsController@update')->name('surveyors.update');
        Route::post('surveyor/add-sub-balance/{id}', 'ManageSurveyorsController@addSubBalance')->name('surveyors.addSubBalance');

resources/views/admin/category.blade.php
@extends('admin.layouts.app')

@section('panel')

<div class="row">
    <div class="col-lg-12 col-md-12 mb-30">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive--sm table-responsive">
                    <table class="table table--light style--two">
                        <thead>
                            <tr>
                                <th scope="col">@lang('nro')</th>
                                <th scope="col">@lang('Nombre')</th>
                                <th scope="col">@lang('Opciones')</th>
                            </tr>
                        </thead>
                        <tbody class="list">
                            @forelse ($categories as $item)
                                <tr>
                                    <td data-label="@lang('Nro')">{{ $loop->index+1 }}</td>
                                    <td data-label="@lang('Nombre')">{{ $item->name }}</td>
                                    <td data-label="@lang('Opciones')">
                                        <a href="#" class="icon-btn  updateBtn" data-route="{{ route('admin.category.update',$item->id) }}" data-resourse="{{$item}}" data-toggle="modal" data-target="#updateBtn" ><i class="la la-pencil-alt"></i></a>
                                        @if ($item->status == 0)
                                            <button type="button"
                                                    class="icon-btn btn--success ml-1 activateBtn"
                                                    data-toggle="modal" data-target="#activateModal"
                                                    data-id="{{$item->id}}"
                                                    data-original-title="@lang('Enable')">
                                                <i class="la la-eye"></i>
                                            </button>
                                        @else
                                            <button type="button"
                                                    class="icon-btn btn--danger ml-1 deactivateBtn"
                                                    data-toggle="modal" data-target="#deactivateModal"
                                                    data-id="{{$item->id}}"
                                                    data-original-title="@lang('Disable')">
                                                <i class="la la-eye-slash"></i>
                                            </button>
                                        @endif
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td class="text-muted text-center" colspan="100%">{{ $empty_message }}</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer py-4">
                {{ $categories->links('admin.partials.paginate') }}
            </div>
        </div>
    </div>
</div>

{{-- Add METHOD MODAL --}}
<div id="addModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"> @lang('Agregar nueva categoria')</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('admin.category.store') }}" method="POST">
                @csrf
                <div class="modal-body">
                    <div class="form-group">
                        <label>@lang('Nombre')</label>
                        <input type="text"class="form-control" placeholder="@lang('Ingrese nombre')" name="name" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn--dark" data-dismiss="modal">@lang('Cerrar')</button>
                    <button type="submit" class="btn btn--primary">@lang('Guardar')</button>
                </div>
            </form>
        </div>
    </div>
</div>


{{-- Update METHOD MODAL --}}
<div id="updateBtn" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"> @lang('Actualizar categoria')</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="" class="edit-route" method="POST">
                @csrf

                <div class="modal-body">
                    <div class="form-group">
                        <label>@lang('Nombre')</label>
                        <input type="text"class="form-control name" placeholder="@lang('Ingrese nombre')" name="name" required>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn--dark" data-dismiss="modal">@lang('Cerrar')</button>
                    <button type="submit" class="btn btn--primary">@lang('Actualizar')</button>
                </div>
            </form>
        </div>
    </div>
</div>

    {{-- ACTIVATE METHOD MODAL --}}
    <div id="activateModal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">@lang('activar categoria ? ')</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{ route('admin.category.activate') }}" method="POST">
                    @csrf
                    <input type="hidden" name="id">
                    <div class="modal-body">
                        <p>@lang('Esta seguro de activar esta categoria ?')</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn--dark" data-dismiss="modal">@lang('Cerrar')</button>
                        <button type="submit" class="btn btn--primary">@lang('Activar')</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    {{-- DEACTIVATE METHOD MODAL --}}
    <div id="deactivateModal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">@lang('Confirmar desactivar categoria')</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{ route('admin.category.deactivate') }}" method="POST">
                    @csrf
                    <input type="hidden" name="id">
                    <div class="modal-body">
                        <p>@lang('Esta seguro de desabilitar esta categoria')</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn--dark" data-dismiss="modal">@lang('Cerrar')</button>
                        <button type="submit" class="btn btn--danger">@lang('Desabilitar')</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    @push('breadcrumb-plugins')
        <div class="btn--search--area">
            <div class="item">
                <a href="javascript:void(0)" class="btn btn-lg btn--primary box--shadow1 text--small addBtn"><i class="fa fa-fw fa-plus"></i>@lang('Agregar nuevo')</a>
            </div>
            <div class="item">
                @if(request()->routeIs('admin.category'))
                    <form action="{{ route('admin.category.search') }}" method="GET" class="form-inline float-sm-right bg--white">
                        <div class="input-group has_append">
                            <input type="text" name="search" class="form-control" placeholder="@lang('Nombre de la catogoria')" value="{{ $search ?? '' }}">
                            <div class="input-group-append">
                                <button class="btn btn--primary" type="submit"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                    </form>
                @else
                    <form action="{{ route('admin.category.search') }}" method="GET" class="form-inline float-sm-right bg--white">
                        <div class="input-group has_append">
                            <input type="text" name="search" class="form-control" placeholder="@lang('Category Name')" value="{{ $search ?? '' }}">
                            <div class="input-group-append">
                                <button class="btn btn--primary" type="submit"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                    </form>
                @endif
            </div>
        </div>
    @endpush
@endsection

@push('script')
<script>
    'use strict';

    (function ($) {
        $('.addBtn').on('click', function () {
            var modal = $('#addModal');
            modal.modal('show');
        });

        $('.updateBtn').on('click', function () {
            var modal = $('#updateBtn');

            var resourse = $(this).data('resourse');

            var route = $(this).data('route');
            $('.name').val(resourse.name);
            $('.edit-route').attr('action',route);

        });

        $('.activateBtn').on('click', function () {
                var modal = $('#activateModal');
                modal.find('input[name=id]').val($(this).data('id'));
            });

            $('.deactivateBtn').on('click', function () {
                var modal = $('#deactivateModal');
                modal.find('input[name=id]').val($(this).data('id'));
            });
    })(jQuery);
</script>
@endpush

resources/views/admin/categoryuser.blade.php
@extends('admin.layouts.app')

@section('panel')

<div class="row">
    <div class="col-lg-12 col-md-12 mb-30">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive--sm table-responsive">
                    <table class="table table--light style--two">
                        <thead>
                            <tr>
                                <th scope="col">@lang('nro')</th>
                                <th scope="col">@lang('Nombre')</th>
                                <th scope="col">@lang('Opciones')</th>
                            </tr>
                        </thead>
                        <tbody class="list">
                            @forelse ($categories as $item)
                                <tr>
                                    <td data-label="@lang('Nro')">{{ $loop->index+1 }}</td>
                                    <td data-label="@lang('Nombre')">{{ $item->name }}</td>
                                    <td data-label="@lang('Opciones')">
                                        <a href="#" class="icon-btn  updateBtn" data-route="{{ route('admin.categoryUser.update',$item->id) }}" data-resourse="{{$item}}" data-toggle="modal" data-target="#updateBtn" ><i class="la la-pencil-alt"></i></a>
                                        @if ($item->status == 0)
                                            <button type="button"
                                                    class="icon-btn btn--success ml-1 activateBtn"
                                                    data-toggle="modal" data-target="#activateModal"
                                                    data-id="{{$item->id}}"
                                                    data-original-title="@lang('Enable')">
                                                <i class="la la-eye"></i>
                                            </button>
                                        @else
                                            <button type="button"
                                                    class="icon-btn btn--danger ml-1 deactivateBtn"
                                                    data-toggle="modal" data-target="#deactivateModal"
                                                    data-id="{{$item->id}}"
                                                    data-original-title="@lang('Disable')">
                                                <i class="la la-eye-slash"></i>
                                            </button>
                                        @endif
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td class="text-muted text-center" colspan="100%">{{ $empty_message }}</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer py-4">
                {{ $categories->links('admin.partials.paginate') }}
            </div>
        </div>
    </div>
</div>

{{-- Add METHOD MODAL --}}
<div id="addModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"> @lang('Agregar nueva categoria')</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('admin.categoryUser.store') }}" method="POST">
                @csrf
                <div class="modal-body">
                    <div class="form-group">
                        <label>@lang('Nombre')</label>
                        <input type="text"class="form-control" placeholder="@lang('Ingrese nombre')" name="name" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn--dark" data-dismiss="modal">@lang('Cerrar')</button>
                    <button type="submit" class="btn btn--primary">@lang('Guardar')</button>
                </div>
            </form>
        </div>
    </div>
</div>


{{-- Update METHOD MODAL --}}
<div id="updateBtn" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"> @lang('Actualizar categoria')</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="" class="edit-route" method="POST">
                @csrf

                <div class="modal-body">
                    <div class="form-group">
                        <label>@lang('Nombre')</label>
                        <input type="text"class="form-control name" placeholder="@lang('Ingrese nombre')" name="name" required>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn--dark" data-dismiss="modal">@lang('Cerrar')</button>
                    <button type="submit" class="btn btn--primary">@lang('Actualizar')</button>
                </div>
            </form>
        </div>
    </div>
</div>

    {{-- ACTIVATE METHOD MODAL --}}
    <div id="activateModal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">@lang('activar categoria ? ')</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{ route('admin.categoryUser.activate') }}" method="POST">
                    @csrf
                    <input type="hidden" name="id">
                    <div class="modal-body">
                        <p>@lang('Esta seguro de activar esta categoria ?')</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn--dark" data-dismiss="modal">@lang('Cerrar')</button>
                        <button type="submit" class="btn btn--primary">@lang('Activar')</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    {{-- DEACTIVATE METHOD MODAL --}}
    <div id="deactivateModal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">@lang('Confirmar desactivar categoria')</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{ route('admin.categoryUser.deactivate') }}" method="POST">
                    @csrf
                    <input type="hidden" name="id">
                    <div class="modal-body">
                        <p>@lang('Esta seguro de desabilitar esta categoria')</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn--dark" data-dismiss="modal">@lang('Cerrar')</button>
                        <button type="submit" class="btn btn--danger">@lang('Desabilitar')</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    @push('breadcrumb-plugins')
        <div class="btn--search--area">
            <div class="item">
                <a href="javascript:void(0)" class="btn btn-lg btn--primary box--shadow1 text--small addBtn"><i class="fa fa-fw fa-plus"></i>@lang('Agregar nuevo')</a>
            </div>
            <div class="item">
                @if(request()->routeIs('admin.category'))
                    <form action="{{ route('admin.categoryUser.search') }}" method="GET" class="form-inline float-sm-right bg--white">
                        <div class="input-group has_append">
                            <input type="text" name="search" class="form-control" placeholder="@lang('Nombre de la catogoria')" value="{{ $search ?? '' }}">
                            <div class="input-group-append">
                                <button class="btn btn--primary" type="submit"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                    </form>
                @else
                    <form action="{{ route('admin.categoryUser.search') }}" method="GET" class="form-inline float-sm-right bg--white">
                        <div class="input-group has_append">
                            <input type="text" name="search" class="form-control" placeholder="@lang('Category Name')" value="{{ $search ?? '' }}">
                            <div class="input-group-append">
                                <button class="btn btn--primary" type="submit"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                    </form>
                @endif
            </div>
        </div>
    @endpush

@endsection

@push('script')
<script>
    'use strict';

    (function ($) {
        $('.addBtn').on('click', function () {
            var modal = $('#addModal');
            modal.modal('show');
        });

        $('.updateBtn').on('click', function () {
            var modal = $('#updateBtn');

            var resourse = $(this).data('resourse');

            var route = $(this).data('route');
            $('.name').val(resourse.name);
            $('.edit-route').attr('action',route);

        });

        $('.activateBtn').on('click', function () {
                var modal = $('#activateModal');
                modal.find('input[name=id]').val($(this).data('id'));
            });

            $('.deactivateBtn').on('click', function () {
                var modal = $('#deactivateModal');
                modal.find('input[name=id]').val($(this).data('id'));
            });
    })(jQuery);
</script>
@endpush