routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/clear', function(){
    \Illuminate\Support\Facades\Artisan::call('optimize:clear');
});

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/


Route::namespace('Gateway')->prefix('ipn')->name('ipn.')->group(function () {
    Route::post('paypal', 'paypal\ProcessController@ipn')->name('paypal');
    Route::get('paypal_sdk', 'paypal_sdk\ProcessController@ipn')->name('paypal_sdk');
    Route::post('perfect_money', 'perfect_money\ProcessController@ipn')->name('perfect_money');
    Route::post('stripe', 'stripe\ProcessController@ipn')->name('stripe');
    Route::post('stripe_js', 'stripe_js\ProcessController@ipn')->name('stripe_js');
    Route::post('stripe_v3', 'stripe_v3\ProcessController@ipn')->name('stripe_v3');
    Route::post('skrill', 'skrill\ProcessController@ipn')->name('skrill');
    Route::post('paytm', 'paytm\ProcessController@ipn')->name('paytm');
    Route::post('payeer', 'payeer\ProcessController@ipn')->name('payeer');
    Route::post('paystack', 'paystack\ProcessController@ipn')->name('paystack');
    Route::post('voguepay', 'voguepay\ProcessController@ipn')->name('voguepay');
    Route::get('flutterwave/{trx}/{type}', 'flutterwave\ProcessController@ipn')->name('flutterwave');
    Route::post('razorpay', 'razorpay\ProcessController@ipn')->name('razorpay');
    Route::post('instamojo', 'instamojo\ProcessController@ipn')->name('instamojo');
    Route::get('blockchain', 'blockchain\ProcessController@ipn')->name('blockchain');
    Route::get('blockio', 'blockio\ProcessController@ipn')->name('blockio');
    Route::post('coinpayments', 'coinpayments\ProcessController@ipn')->name('coinpayments');
    Route::post('coinpayments_fiat', 'coinpayments_fiat\ProcessController@ipn')->name('coinpayments_fiat');
    Route::post('coingate', 'coingate\ProcessController@ipn')->name('coingate');
    Route::post('coinbase_commerce', 'coinbase_commerce\ProcessController@ipn')->name('coinbase_commerce');
    Route::get('mollie', 'mollie\ProcessController@ipn')->name('mollie');
    Route::post('cashmaal', 'cashmaal\ProcessController@ipn')->name('cashmaal');
});

// User Support Ticket
Route::prefix('ticket')->group(function () {
    Route::get('/', 'TicketController@supportTicket')->name('ticket');
    Route::get('/new', 'TicketController@openSupportTicket')->name('ticket.open');
    Route::post('/create', 'TicketController@storeSupportTicket')->name('ticket.store');
    Route::get('/view/{ticket}', 'TicketController@viewTicket')->name('ticket.view');
    Route::get('/user-view/{ticket}', 'TicketController@viewUserTicket')->name('ticket.view.user');
    Route::post('/reply/{ticket}', 'TicketController@replyTicket')->name('ticket.reply');
    Route::get('/download/{ticket}', 'TicketController@ticketDownload')->name('ticket.download');
});

// User Support Ticket
Route::prefix('ticket')->group(function () {
    Route::get('surveyor/ticket/', 'SurveyorTicketController@supportTicket')->name('surveyor.ticket');
    Route::get('surveyor/ticket/new', 'SurveyorTicketController@openSupportTicket')->name('surveyor.ticket.open');
    Route::post('surveyor/ticket/create', 'SurveyorTicketController@storeSupportTicket')->name('surveyor.ticket.store');
    Route::get('surveyor/ticket/view/{ticket}', 'SurveyorTicketController@viewTicket')->name('surveyor.ticket.view');
    Route::post('surveyor/ticket/reply/{ticket}', 'SurveyorTicketController@replyTicket')->name('surveyor.ticket.reply');
    Route::get('surveyor/ticket/download/{ticket}', 'SurveyorTicketController@ticketDownload')->name('surveyor.ticket.download');
});


/*
|--------------------------------------------------------------------------
| Start Admin Area
|--------------------------------------------------------------------------
*/

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {
    Route::namespace('Auth')->group(function () {
        Route::get('/', 'LoginController@showLoginForm')->name('login');
        Route::post('/', 'LoginController@login')->name('login');
        Route::get('logout', 'LoginController@logout')->name('logout');

        // Admin Password Reset
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.reset');
        Route::post('password/reset', 'ForgotPasswordController@sendResetLinkEmail');
        Route::post('password/verify-code', 'ForgotPasswordController@verifyCode')->name('password.verify-code');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.change-link');
        Route::post('password/reset/change', 'ResetPasswordController@reset')->name('password.change');
    });

    Route::middleware(['admin','access'])->group(function () {
        Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
        Route::get('profile', 'AdminController@profile')->name('profile');
        Route::post('profile', 'AdminController@profileUpdate')->name('profile.update');
        Route::get('password', 'AdminController@password')->name('password');
        Route::post('password', 'AdminController@passwordUpdate')->name('password.update');

        //Manage Category
        Route::get('category', 'CategoryController@categories')->name('category');
        Route::post('category/new', 'CategoryController@storeCategory')->name('category.store');
        Route::get('category-user', 'CategoryController@categoriesUser')->name('categoryUser');
        Route::post('category-user/new', 'CategoryController@storeCategoryUser')->name('categoryUser.store');
        Route::post('category/update/{id}', 'CategoryController@updateCategory')->name('category.update');
        Route::post('category-user/update/{id}', 'CategoryController@updateCategoryUser')->name('categoryUser.update');
        Route::get('category/search', 'CategoryController@searchCategory')->name('category.search');
        Route::get('category-user/search', 'CategoryController@searchCategoryUser')->name('categoryUser.search');
        Route::post('category/activate', 'CategoryController@activate')->name('category.activate');
        Route::post('category/deactivate', 'CategoryController@deactivate')->name('category.deactivate');
        Route::post('category-user/activate', 'CategoryController@activateUser')->name('categoryUser.activate');
        Route::post('category-user/deactivate', 'CategoryController@deactivateUser')->name('categoryUser.deactivate');

        // Users Manager
        Route::get('users', 'ManageUsersController@allUsers')->name('users.all');
        Route::get('users/active', 'ManageUsersController@activeUsers')->name('users.active');
        Route::get('users/banned', 'ManageUsersController@bannedUsers')->name('users.banned');
        Route::get('users/email-verified', 'ManageUsersController@emailVerifiedUsers')->name('users.emailVerified');
        Route::get('users/email-unverified', 'ManageUsersController@emailUnverifiedUsers')->name('users.emailUnverified');
        Route::get('users/sms-unverified', 'ManageUsersController@smsUnverifiedUsers')->name('users.smsUnverified');
        Route::get('users/sms-verified', 'ManageUsersController@smsVerifiedUsers')->name('users.smsVerified');

        Route::get('users/{scope}/search', 'ManageUsersController@search')->name('users.search');
        Route::get('user/detail/{id}', 'ManageUsersController@detail')->name('users.detail');
        Route::post('user/update/{id}', 'ManageUsersController@update')->name('users.update');
        Route::delete('user/delete/{id}', 'ManageUsersController@delete')->name('users.destroy');
        Route::post('user/add-sub-balance/{id}', 'ManageUsersController@addSubBalance')->name('users.addSubBalance');
        Route::get('user/send-email/{id}', 'ManageUsersController@showEmailSingleForm')->name('users.email.single');
        Route::post('user/send-email/{id}', 'ManageUsersController@sendEmailSingle')->name('users.email.single');
        Route::get('user/transactions/{id}', 'ManageUsersController@transactions')->name('users.transactions');
        Route::get('user/deposits/via/{method}/{type?}/{userId}', 'ManageUsersController@depViaMethod')->name('users.deposits.method');
        Route::get('user/withdrawals/{id}', 'ManageUsersController@withdrawals')->name('users.withdrawals');
        Route::get('user/withdrawals/via/{method}/{type?}/{userId}', 'ManageUsersController@withdrawalsViaMethod')->name('users.withdrawals.method');

        // Surveyors Manager
        Route::get('surveyors', 'ManageSurveyorsController@allSurveyors')->name('surveyors.all');
        Route::get('surveyors/active', 'ManageSurveyorsController@activeSurveyors')->name('surveyors.active');
        Route::get('surveyors/banned', 'ManageSurveyorsController@bannedSurveyors')->name('surveyors.banned');
        Route::get('surveyors/email-verified', 'ManageSurveyorsController@emailVerifiedSurveyors')->name('surveyors.emailVerified');
        Route::get('surveyors/email-unverified', 'ManageSurveyorsController@emailUnverifiedSurveyors')->name('surveyors.emailUnverified');
        Route::get('surveyors/sms-unverified', 'ManageSurveyorsController@smsUnverifiedSurveyors')->name('surveyors.smsUnverified');
        Route::get('surveyors/sms-verified', 'ManageSurveyorsController@smsVerifiedSurveyors')->name('surveyors.smsVerified');

        Route::get('surveyors/{scope}/search', 'ManageSurveyorsController@search')->name('surveyors.search');
        Route::get('surveyor/detail/{id}', 'ManageSurveyorsController@detail')->name('surveyors.detail');
        Route::post('surveyor/update/{id}', 'ManageSurveyorsController@update')->name('surveyors.update');
        Route::post('surveyor/add-sub-balance/{id}', 'ManageSurveyorsController@addSubBalance')->name('surveyors.addSubBalance');

app/Survey.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Survey extends Model
{
    protected $guarded = ['id'];
    // protected $fillable = ['nombre', 'email', 'otros_campos'];
    protected $casts = [
        'users' => 'array',
        'country' => 'array'
    ];

    public function surveyor()
    {
        return $this->belongsTo(Surveyor::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function questions()
    {
        return $this->hasMany(Question::class);
    }

    public function answers()
    {
        return $this->hasMany(Answer::class);
    }
}

app/Http/Controllers/Admin/SurveyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Question;
use App\Survey;
use Illuminate\Http\Request;

class SurveyController extends Controller
{
    public function pending(){
        $page_title = 'Pending Survey';
        $empty_message = 'No pending survey';

        $surveys = Survey::where('status',1)->whereHas('surveyor', function($q){
            $q->where('status',1);
        })->paginate(getPaginate());

        return view('admin.survey.index',compact('page_title','empty_message','surveys'));
    }

    public function approved(){
        $page_title = 'Encuestas';
        $empty_message = 'Lista vacia';

        $surveys = Survey::whereHas('surveyor', function($q){
            $q->where('status',1);
        })->paginate(getPaginate());

        return view('admin.survey.index',compact('page_title','empty_message','surveys'));
    }

    public function rejected(){
        $page_title = 'Rejected Survey';
        $empty_message = 'No rejected survey';

        $surveys = Survey::where('status',3)->whereHas('surveyor', function($q){
            $q->where('status',1);
        })->paginate(getPaginate());

        return view('admin.survey.index',compact('page_title','empty_message','surveys'));
    }

    public function approve(Request $request, $id){
        $survey = Survey::findOrFail($id);
        $survey->status = 0;
        $survey->save();

        $notify[] = ['success', 'Approved Successfully'];
        return back()->withNotify($notify);
    }

    public function reject(Request $request, $id){
        $survey = Survey::findOrFail($id);
        $survey->status = 3;
        $survey->save();

        $notify[] = ['success', 'Rejected Successfully'];
        return back()->withNotify($notify);
    }

    public function search(Request $request, $scope)
    {
        $search = $request->search;
        $surveys = Survey::whereHas('surveyor', function($q){
            $q->where('status',1);
        })->where(function($query) use($search){
            $query->whereHas('category', function($d) use($search) {
                $d->where('name', 'like', "%$search%");
            })->orWhere('name', 'like', "%$search%");
        });


        $page_title = '';

        switch ($scope) {
            case 'pending':
                $page_title .= 'Pending ';
                $surveys = $surveys->where('status', 1);
                break;
            case 'approved':
                $page_title .= 'Approved ';
                $surveys = $surveys->where('status', 0);
                break;
            case 'rejected':
                $page_title .= 'Rejected ';
                $surveys = $surveys->where('status', 3);
                break;
        }
        $surveys = $surveys->paginate(getPaginate());
        $page_title .= 'Survey Search - ' . $search;
        $empty_message = 'No search result found';
        return view('admin.survey.index', compact('page_title', 'search', 'scope', 'empty_message', 'surveys'));
    }

    public function questionAll($id)
    {
        $page_title = 'Preguntas';
        $survey = Survey::findOrFail($id);
        $questions = $survey->questions()->paginate(getPaginate());
        $empty_message = 'Sin datos';
        return view('admin.survey.question', compact('page_title','survey','empty_message','questions'));
    }

    public function questionView($q_id,$s_id)
    {
        $question = Question::findOrFail($q_id);

        if ($question->survey_id != $s_id) {
            $notify[] = ['error', 'Something went Wrong  '];
            return back()->withNotify($notify);
        }

        $page_title = 'Ver preguntas';
        return view('admin.survey.view',compact('page_title','question'));
    }
}

resources/views/admin/survey/index.blade.php
@extends('admin.layouts.app')
@section('panel')
    <div class="row">
        <div class="col-lg-12">
            <div class="card b-radius--10 ">
                <div class="card-body p-0">
                    <div class="table-responsive--md  table-responsive">
                        <table class="table table--light style--two">
                            <thead>
                                <tr>
                                    <th scope="col">@lang('Nro')</th>
                                    <th scope="col">@lang('Categoria')</th>
                                    <th scope="col">@lang('Imagen')</th>
                                    <th scope="col">@lang('Nombre')</th>
                                    <th scope="col">@lang('Creador de Formularios')</th>
                                    <!-- <th scope="col">@lang('Estado')</th> -->
                                    <th scope="col">@lang('Preguntas')</th>
                                    <th scope="col">@lang('fecha de creación')</th>
                                    <th scope="col">@lang('Preguntas')</th>
                                </tr>
                            </thead>
                            <tbody>

                                @forelse($surveys as $item)
                                    <tr>
                                        <td data-label="@lang('Nro')">{{$loop->index+1}}</td>
                                        <td data-label="@lang('Categoria')">{{__($item->category->name)}}</td>
                                        <td data-label="@lang('Imagen')">
                                            <div class="user">
                                                <div class="thumb">
                                                    <img src="{{ getImage(imagePath()['survey']['path'].'/'.$item->image,imagePath()['survey']['size'])}}" alt="@lang('image')">
                                                </div>
                                            </div>
                                        </td>
                                        <td data-label="@lang('Nombre')">{{__($item->name)}}</td>
                                        <td data-label="@lang('Creador de Formularios')">
                                            <a href="{{ route('admin.surveyors.detail', $item->surveyor->id) }}">{{ $item->surveyor->username }}</a>
                                        </td>
                                        <!-- <td data-label="@lang('Status')">
                                            @if ($item->status == 0)
                                                <span class="text--small badge font-weight-normal badge--success">@lang('Approved')</span>
                                            @elseif($item->status == 1)
                                                <span class="text--small badge font-weight-normal badge--warning">@lang('Pending')</span>
                                            @elseif($item->status == 3)
                                                <span class="text--small badge font-weight-normal badge--danger">@lang('Rejected')</span>
                                            @endif
                                        </td> -->
                                        <td data-label="@lang('Preguntas')">{{ $item->questions->count() }}</td>
                                        <td data-label="@lang('Fecha de Creacion')">{{ showDateTime($item->created_at) }}</td>
                                        <td data-label="@lang('Preguntas')">

                                            <a href="{{route('admin.manage.survey.question.all',$item->id)}}" class="icon-btn mr-1" data-toggle="tooltip" title="@lang('Preguntas')" data-original-title="@lang('Preguntas')">
                                                <i class="fas fa-question-circle text--shadow"></i>
                                            </a>

                                            @if ($item->status == 1)
                                                <a href="javascript:void(0)" class="icon-btn btn--success mr-1 approveBtn" data-toggle="tooltip" title="@lang('Preguntas')" data-original-title="@lang('Approve')" data-url="{{route('admin.manage.survey.approve',$item->id)}}">
                                                    <i class="fas fa-check-circle text--shadow"></i>
                                                </a>

                                                <a href="javascript:void(0)" class="icon-btn btn--danger rejectBtn" data-toggle="tooltip" title="@lang('Reject')" data-original-title="@lang('Reject')" data-url="{{route('admin.manage.survey.reject',$item->id)}}">
                                                    <i class="las la-ban text--shadow"></i>
                                                </a>
                                            @endif
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td class="text-muted text-center" colspan="100%">{{ __($empty_message) }}</td>
                                    </tr>
                                @endforelse

                            </tbody>
                        </table><!-- table end -->
                    </div>
                </div>
                <div class="card-footer py-4">
                    {{ $surveys->links('admin.partials.paginate') }}
                </div>
            </div><!-- card end -->
        </div>
    </div>

    {{-- Approve MODAL --}}
    <div class="modal fade" id="approveModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">@lang('Approve Survey')</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <form method="post" action="">
                    @csrf
                    <div class="modal-body">
                        <p class="text-muted">@lang('Are you sure you want to Approve?')</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn--dark" data-dismiss="modal">@lang('Close')</button>
                        <button type="submit" class="btn btn--success approveButton">@lang('Approve')</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    {{-- DELETE MODAL --}}
    <div class="modal fade" id="rejectModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">@lang('Remove Survey')</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <form method="post" action="">
                    @csrf
                    <div class="modal-body">
                        <p class="text-muted">@lang('Are you sure you want to Reject?')</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn--dark" data-dismiss="modal">@lang('Close')</button>
                        <button type="submit" class="btn btn--danger deleteButton">@lang('Reject')</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@push('breadcrumb-plugins')
    <form action="{{ route('admin.manage.survey.search', $scope ?? str_replace('admin.manage.survey.', '', request()->route()->getName())) }}" method="GET" class="form-inline float-sm-right bg--white">
        <div class="input-group has_append">
            <input type="text" name="search" class="form-control" placeholder="@lang('Survey category name')" value="{{ $search ?? '' }}">
            <div class="input-group-append">
                <button class="btn btn--primary" type="submit"><i class="fa fa-search"></i></button>
            </div>
        </div>
    </form>
@endpush

@push('script')
    <script>
        (function($){
            "use strict";

            $('.rejectBtn').on('click', function () {
                var modal = $('#rejectModal');
                var url = $(this).data('url');

                modal.find('form').attr('action', url);
                modal.modal('show');
            });

            $('.approveBtn').on('click', function () {
                var modal = $('#approveModal');
                var url = $(this).data('url');

                modal.find('form').attr('action', url);
                modal.modal('show');
            });
        })(jQuery);
    </script>
@endpush

resources/views/admin/survey/question.blade.php
@extends('admin.layouts.app')
@section('panel')
    <div class="row">
        <div class="col-lg-12">
            <div class="card b-radius--10 ">
                <div class="card-body p-0">
                    <div class="table-responsive--md  table-responsive">
                        <table class="table table--light style--two">
                            <thead>
                                <tr>
                                    <th scope="col">@lang('nro')</th>
                                    <th scope="col">@lang('Pregunta')</th>
                                    <th scope="col">@lang('Todas las opciones')</th>
                                    <th scope="col">@lang('Tipo')</th>
                                    <!-- <th scope="col">@lang('Personalizado')</th> -->
                                    <th scope="col">@lang('Opciones')</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($questions as $item)
                                    <tr>
                                        <td data-label="@lang('SL')">{{$loop->index+1}}</td>
                                        <td data-label="@lang('Question')">{{__($item->question)}}</td>
                                        <td data-label="@lang('Total Options')">{{@count($item->options)}}</td>
                                        <td data-label="@lang('Type')">
                                        @if ($item->type == 1)
                                                    @lang('Opcion unica')
                                                @elseif ($item->type == 2)
                                                    @lang('Opcion Multiple')
                                                @elseif ($item->type == 3)
                                                    @lang('Respuesta Corta')
                                                @elseif ($item->type == 4)
                                                    @lang('Respuesta larga')
                                                @elseif ($item->type == 5)
                                                    @lang('Casilla de verificacion')
                                                @elseif ($item->type == 6)
                                                    @lang('Desplegable')
                                                @elseif ($item->type == 7)
                                                    @lang('Cargar Archivos')
                                                @elseif ($item->type == 8)
                                                    @lang('Fecha')
                                                @elseif ($item->type == 9)
                                                    @lang('Hora')
                                                @elseif ($item->type == 10)
                                                    @lang('Escala')
                                                @endif
                                        </td>
                                        <!-- <td data-label="@lang('Custom Input')">
                                            @if ($item->custom_input == 0)
                                                @lang('No')
                                            @elseif ($item->custom_input == 1)
                                                @lang('Yes')
                                            @endif
                                        </td> -->
                                        <td data-label="@lang('Action')"><a href="{{route('admin.manage.survey.question.view',[$item->id,$survey->id])}}" class="icon-btn"><i class="la la-eye"></i></a></td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td class="text-center" colspan="100%">{{__($empty_message)}}</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table><!-- table end -->
                    </div>
                </div>
                <div class="card-footer py-4">
                    {{ $questions->links('admin.partials.paginate') }}
                </div>
            </div><!-- card end -->
        </div>
    </div>
@endsection

@push('breadcrumb-plugins')
    <a href="javascript:window.history.back();" class="btn btn-sm btn--primary box--shadow1 text--small"><i class="las la-angle-double-left"></i>@lang('Volver')</a>
@endpush