routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/clear', function(){
    \Illuminate\Support\Facades\Artisan::call('optimize:clear');
});

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/


Route::namespace('Gateway')->prefix('ipn')->name('ipn.')->group(function () {
    Route::post('paypal', 'paypal\ProcessController@ipn')->name('paypal');
    Route::get('paypal_sdk', 'paypal_sdk\ProcessController@ipn')->name('paypal_sdk');
    Route::post('perfect_money', 'perfect_money\ProcessController@ipn')->name('perfect_money');
    Route::post('stripe', 'stripe\ProcessController@ipn')->name('stripe');
    Route::post('stripe_js', 'stripe_js\ProcessController@ipn')->name('stripe_js');
    Route::post('stripe_v3', 'stripe_v3\ProcessController@ipn')->name('stripe_v3');
    Route::post('skrill', 'skrill\ProcessController@ipn')->name('skrill');
    Route::post('paytm', 'paytm\ProcessController@ipn')->name('paytm');
    Route::post('payeer', 'payeer\ProcessController@ipn')->name('payeer');
    Route::post('paystack', 'paystack\ProcessController@ipn')->name('paystack');
    Route::post('voguepay', 'voguepay\ProcessController@ipn')->name('voguepay');
    Route::get('flutterwave/{trx}/{type}', 'flutterwave\ProcessController@ipn')->name('flutterwave');
    Route::post('razorpay', 'razorpay\ProcessController@ipn')->name('razorpay');
    Route::post('instamojo', 'instamojo\ProcessController@ipn')->name('instamojo');
    Route::get('blockchain', 'blockchain\ProcessController@ipn')->name('blockchain');
    Route::get('blockio', 'blockio\ProcessController@ipn')->name('blockio');
    Route::post('coinpayments', 'coinpayments\ProcessController@ipn')->name('coinpayments');
    Route::post('coinpayments_fiat', 'coinpayments_fiat\ProcessController@ipn')->name('coinpayments_fiat');
    Route::post('coingate', 'coingate\ProcessController@ipn')->name('coingate');
    Route::post('coinbase_commerce', 'coinbase_commerce\ProcessController@ipn')->name('coinbase_commerce');
    Route::get('mollie', 'mollie\ProcessController@ipn')->name('mollie');
    Route::post('cashmaal', 'cashmaal\ProcessController@ipn')->name('cashmaal');
});

// User Support Ticket
Route::prefix('ticket')->group(function () {
    Route::get('/', 'TicketController@supportTicket')->name('ticket');
    Route::get('/new', 'TicketController@openSupportTicket')->name('ticket.open');
    Route::post('/create', 'TicketController@storeSupportTicket')->name('ticket.store');
    Route::get('/view/{ticket}', 'TicketController@viewTicket')->name('ticket.view');
    Route::get('/user-view/{ticket}', 'TicketController@viewUserTicket')->name('ticket.view.user');
    Route::post('/reply/{ticket}', 'TicketController@replyTicket')->name('ticket.reply');
    Route::get('/download/{ticket}', 'TicketController@ticketDownload')->name('ticket.download');
});

// User Support Ticket
Route::prefix('ticket')->group(function () {
    Route::get('surveyor/ticket/', 'SurveyorTicketController@supportTicket')->name('surveyor.ticket');
    Route::get('surveyor/ticket/new', 'SurveyorTicketController@openSupportTicket')->name('surveyor.ticket.open');
    Route::post('surveyor/ticket/create', 'SurveyorTicketController@storeSupportTicket')->name('surveyor.ticket.store');
    Route::get('surveyor/ticket/view/{ticket}', 'SurveyorTicketController@viewTicket')->name('surveyor.ticket.view');
    Route::post('surveyor/ticket/reply/{ticket}', 'SurveyorTicketController@replyTicket')->name('surveyor.ticket.reply');
    Route::get('surveyor/ticket/download/{ticket}', 'SurveyorTicketController@ticketDownload')->name('surveyor.ticket.download');
});


/*
|--------------------------------------------------------------------------
| Start Admin Area
|--------------------------------------------------------------------------
*/

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {
    Route::namespace('Auth')->group(function () {
        Route::get('/', 'LoginController@showLoginForm')->name('login');
        Route::post('/', 'LoginController@login')->name('login');
        Route::get('logout', 'LoginController@logout')->name('logout');

        // Admin Password Reset
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.reset');
        Route::post('password/reset', 'ForgotPasswordController@sendResetLinkEmail');
        Route::post('password/verify-code', 'ForgotPasswordController@verifyCode')->name('password.verify-code');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.change-link');
        Route::post('password/reset/change', 'ResetPasswordController@reset')->name('password.change');
    });

    Route::middleware(['admin','access'])->group(function () {
        Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
        Route::get('profile', 'AdminController@profile')->name('profile');
        Route::post('profile', 'AdminController@profileUpdate')->name('profile.update');
        Route::get('password', 'AdminController@password')->name('password');
        Route::post('password', 'AdminController@passwordUpdate')->name('password.update');

        //Manage Category
        Route::get('category', 'CategoryController@categories')->name('category');
        Route::post('category/new', 'CategoryController@storeCategory')->name('category.store');
        Route::get('category-user', 'CategoryController@categoriesUser')->name('categoryUser');
        Route::post('category-user/new', 'CategoryController@storeCategoryUser')->name('categoryUser.store');
        Route::post('category/update/{id}', 'CategoryController@updateCategory')->name('category.update');
        Route::post('category-user/update/{id}', 'CategoryController@updateCategoryUser')->name('categoryUser.update');
        Route::get('category/search', 'CategoryController@searchCategory')->name('category.search');
        Route::get('category-user/search', 'CategoryController@searchCategoryUser')->name('categoryUser.search');
        Route::post('category/activate', 'CategoryController@activate')->name('category.activate');
        Route::post('category/deactivate', 'CategoryController@deactivate')->name('category.deactivate');
        Route::post('category-user/activate', 'CategoryController@activateUser')->name('categoryUser.activate');
        Route::post('category-user/deactivate', 'CategoryController@deactivateUser')->name('categoryUser.deactivate');

        // Users Manager
        Route::get('users', 'ManageUsersController@allUsers')->name('users.all');
        Route::get('users/active', 'ManageUsersController@activeUsers')->name('users.active');
        Route::get('users/banned', 'ManageUsersController@bannedUsers')->name('users.banned');
        Route::get('users/email-verified', 'ManageUsersController@emailVerifiedUsers')->name('users.emailVerified');
        Route::get('users/email-unverified', 'ManageUsersController@emailUnverifiedUsers')->name('users.emailUnverified');
        Route::get('users/sms-unverified', 'ManageUsersController@smsUnverifiedUsers')->name('users.smsUnverified');
        Route::get('users/sms-verified', 'ManageUsersController@smsVerifiedUsers')->name('users.smsVerified');

        Route::get('users/{scope}/search', 'ManageUsersController@search')->name('users.search');
        Route::get('user/detail/{id}', 'ManageUsersController@detail')->name('users.detail');
        Route::post('user/update/{id}', 'ManageUsersController@update')->name('users.update');
        Route::delete('user/delete/{id}', 'ManageUsersController@delete')->name('users.destroy');
        Route::post('user/add-sub-balance/{id}', 'ManageUsersController@addSubBalance')->name('users.addSubBalance');
        Route::get('user/send-email/{id}', 'ManageUsersController@showEmailSingleForm')->name('users.email.single');
        Route::post('user/send-email/{id}', 'ManageUsersController@sendEmailSingle')->name('users.email.single');
        Route::get('user/transactions/{id}', 'ManageUsersController@transactions')->name('users.transactions');
        Route::get('user/deposits/via/{method}/{type?}/{userId}', 'ManageUsersController@depViaMethod')->name('users.deposits.method');
        Route::get('user/withdrawals/{id}', 'ManageUsersController@withdrawals')->name('users.withdrawals');
        Route::get('user/withdrawals/via/{method}/{type?}/{userId}', 'ManageUsersController@withdrawalsViaMethod')->name('users.withdrawals.method');

        // Surveyors Manager
        Route::get('surveyors', 'ManageSurveyorsController@allSurveyors')->name('surveyors.all');
        Route::get('surveyors/active', 'ManageSurveyorsController@activeSurveyors')->name('surveyors.active');
        Route::get('surveyors/banned', 'ManageSurveyorsController@bannedSurveyors')->name('surveyors.banned');
        Route::get('surveyors/email-verified', 'ManageSurveyorsController@emailVerifiedSurveyors')->name('surveyors.emailVerified');
        Route::get('surveyors/email-unverified', 'ManageSurveyorsController@emailUnverifiedSurveyors')->name('surveyors.emailUnverified');
        Route::get('surveyors/sms-unverified', 'ManageSurveyorsController@smsUnverifiedSurveyors')->name('surveyors.smsUnverified');
        Route::get('surveyors/sms-verified', 'ManageSurveyorsController@smsVerifiedSurveyors')->name('surveyors.smsVerified');

        Route::get('surveyors/{scope}/search', 'ManageSurveyorsController@search')->name('surveyors.search');
        Route::get('surveyor/detail/{id}', 'ManageSurveyorsController@detail')->name('surveyors.detail');
        Route::post('surveyor/update/{id}', 'ManageSurveyorsController@update')->name('surveyors.update');
        Route::post('surveyor/add-sub-balance/{id}', 'ManageSurveyorsController@addSubBalance')->name('surveyors.addSubBalance');

resources/views/admin/partials/breadcrumb.blade.php
<div class="row align-items-center mb-30 justify-content-between">
    <div class="col-lg-6 col-sm-6">
        <h6 class="page-title">Panel</h6>
    </div>
    <div class="col-lg-6 col-sm-6 text-sm-right mt-sm-0 mt-3 right-part">
        @stack('breadcrumb-plugins')
    </div>
</div>

resources/views/admin/partials/notify.blade.php
<link rel="stylesheet" href="{{ asset('assets/admin/css/iziToast.min.css') }}">
<script src="{{ asset('assets/admin/js/iziToast.min.js') }}"></script>
@if(session()->has('notify'))
    @foreach(session('notify') as $msg)
        <script> 
            "use strict";
            iziToast.{{ $msg[0] }}({message:"{{ __($msg[1]) }}", position: "topRight"}); 
        </script>
    @endforeach
@endif

@if ($errors->any())
    @php
        $collection = collect($errors->all());
        $errors = $collection->unique();
    @endphp

    <script>
        "use strict";
        @foreach ($errors as $error)
        iziToast.error({
            message: '{{ __($error) }}',
            position: "topRight"
        });
        @endforeach
    </script>

@endif
<script>
"use strict";
    function notify(status,message) {
        iziToast[status]({
            message: message,
            position: "topRight"
        });
    }
</script>

resources/views/admin/partials/paginate.blade.php
<nav aria-label="...">
    <ul class="pagination justify-content-end mb-0">
        @if ($paginator->onFirstPage())

        @else
            <li class="page-item ">
                <a class="page-link" href="{{ $paginator->previousPageUrl() }}" tabindex="-1">
                    <i class="fa fa-angle-left"></i>
                    <span class="sr-only">@lang('Previous')</span>
                </a>
            </li>
        @endif


        @foreach ($elements as $element)
            @if (is_string($element))
                <li class="page-item disabled">
                    <a class="page-link" href="javascript:void(0)">
                        {{ __($element) }}
                    </a>
                </li>
            @endif
            @if (is_array($element))
                @if(count($element) < 2)
                    @foreach ($element as $page => $url)

                    @endforeach
                @else
                    @foreach ($element as $page => $url)
                        @if ($page == $paginator->currentPage())
                            <li class="page-item active">
                                <a class="page-link" href="javascript:void(0)">{{ __($page) }}</a>
                            </li>
                        @else
                            <li class="page-item ">
                                <a class="page-link" href="{{ $url }}">{{ __($page) }}</a>
                            </li>
                        @endif
                    @endforeach
                @endif
            @endif
        @endforeach
        @if ($paginator->hasMorePages())
            <li class="page-item">
                <a class="page-link" href="{{ $paginator->nextPageUrl() }}">
                    <i class="fa fa-angle-right"></i>
                    <span class="sr-only">@lang('Next')</span>
                </a>
            </li>
        @else
            <li>
            </li>
        @endif
    </ul>
</nav>

resources/views/admin/partials/sidenav.blade.php
<div class="sidebar capsule--rounded bg_img overlay--dark"
     data-background="{{getImage('assets/admin/images/sidebar/3.jpg','400x800')}}">
    <button class="res-sidebar-close-btn"><i class="las la-times"></i></button>
    <div class="sidebar__inner">
        <div class="sidebar__logo">
            <a href="{{route('admin.dashboard')}}" class="sidebar__main-logo"><img
                    src="{{getImage(imagePath()['logoIcon']['path'] .'/logo.png')}}" alt="@lang('image')"></a>
            <a href="{{route('admin.dashboard')}}" class="sidebar__logo-shape"><img
                    src="{{getImage(imagePath()['logoIcon']['path'] .'/favicon.png')}}" alt="@lang('image')"></a>
            <button type="button" class="navbar__expand"></button>
        </div>

        <div class="sidebar__menu-wrapper" id="sidebar__menuWrapper">
            <ul class="sidebar__menu">
                <li class="sidebar-menu-item {{menuActive('admin.dashboard')}}">
                    <a href="{{route('admin.dashboard')}}" class="nav-link ">
                        <i class="menu-icon las la-home"></i>
                        <span class="menu-title">@lang('Panel')</span>
                    </a>
                </li>

                <li class="sidebar-menu-item {{menuActive('admin.category*')}}">
                    <a href="{{route('admin.category')}}" class="nav-link ">
                        <i class="menu-icon las la-tags"></i>
                        <span class="menu-title">@lang('Tipo de Formulario')</span>
                    </a>
                </li> 
                <li class="sidebar-menu-item {{menuActive('admin.categoryUser*')}}">
                    <a href="{{route('admin.categoryUser')}}" class="nav-link ">
                        <i class="menu-icon las la-tags"></i>
                        <span class="menu-title">@lang('Categoria de usuarios')</span>
                    </a>
                </li>

                <li class="sidebar-menu-item sidebar-dropdown">
                    <a href="javascript:void(0)" class="{{menuActive('admin.manage.survey*',3)}}">
                        <i class="menu-icon lar la-question-circle"></i>
                        <span class="menu-title">@lang('Gestion Formularios') </span>
                        @if($pending_survey_count > 0)
                            <span class="menu-badge pill bg--primary ml-auto">
                                <i class="fa fa-exclamation"></i>
                            </span>
                        @endif
                    </a>
                    <div class="sidebar-submenu {{menuActive('admin.manage.survey*',2)}} ">
                        <ul>
                            <li class="sidebar-menu-item {{menuActive('admin.manage.survey.approved')}}">
                                <a href="{{route('admin.manage.survey.approved')}}" class="nav-link">
                                    <i class="menu-icon las la-dot-circle"></i>
                                    <span class="menu-title">@lang('Lista de Formularios')</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>

                <!-- <li class="sidebar-menu-item sidebar-dropdown">
                    <a href="javascript:void(0)" class="{{menuActive('admin.surveyors*',3)}}">
                        <i class="menu-icon las la-users"></i>
                        <span class="menu-title">@lang('Encuestadores')</span>
                    </a>
                    <div class="sidebar-submenu {{menuActive('admin.surveyors*',2)}} ">
                        <ul>
                            <li class="sidebar-menu-item {{menuActive('admin.surveyors.all')}} ">
                                <a href="{{route('admin.surveyors.all')}}" class="nav-link">
                                    <i class="menu-icon las la-dot-circle"></i>
                                    <span class="menu-title">@lang('Lista de encuestadores')</span>
                                </a>
                            </li>

                        </ul>
                    </div>
                </li> -->

                <li class="sidebar-menu-item sidebar-dropdown">
                    <a href="javascript:void(0)" class="{{menuActive('admin.users*',3)}}">
                        <i class="menu-icon las la-users"></i>
                        <span class="menu-title">@lang('Usuarios')</span>
                    </a>
                    <div class="sidebar-submenu {{menuActive('admin.users*',2)}} ">
                        <ul>
                            <li class="sidebar-menu-item {{menuActive('admin.users.all')}} ">
                                <a href="{{route('admin.users.all')}}" class="nav-link">
                                    <i class="menu-icon las la-dot-circle"></i>
                                    <span class="menu-title">@lang('Todos los usuarios')</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- sidebar end -->

resources/views/admin/partials/topnav.blade.php
<!-- navbar-wrapper start -->
<nav class="navbar-wrapper">
    <form class="navbar-search" onsubmit="return false;">
        <button type="submit" class="navbar-search__btn">
            <i class="las la-search"></i>
        </button>
        <input type="search" name="navbar-search__field" id="navbar-search__field"
               placeholder="Search...">
        <button type="button" class="navbar-search__close"><i class="las la-times"></i></button>

        <div id="navbar_search_result_area">
            <ul class="navbar_search_result"></ul>
        </div>
    </form>

    <div class="navbar__left">
        <button class="res-sidebar-open-btn"><i class="las la-bars"></i></button>
        <button type="button" class="fullscreen-btn">
            <i class="fullscreen-open las la-compress" onclick="openFullscreen();"></i>
            <i class="fullscreen-close las la-compress-arrows-alt" onclick="closeFullscreen();"></i>
        </button>
    </div>

    <div class="navbar__right">
        <ul class="navbar__action-list">
            <li>
                <button type="button" class="navbar-search__btn-open">
                    <i class="las la-search"></i>
                </button>
            </li>


            <li class="dropdown">
                <button type="button" class="" data-toggle="dropdown" data-display="static" aria-haspopup="true"
                        aria-expanded="false">


          <span class="navbar-user">
            <span class="navbar-user__thumb"><img
                    src="{{ getImage('assets/admin/images/profile/'. auth()->guard('admin')->user()->image) }}"
                    alt="image"></span>

            <span class="navbar-user__info">
              <span class="navbar-user__name">{{auth()->guard('admin')->user()->username}}</span>
            </span>
            <span class="icon"><i class="las la-chevron-circle-down"></i></span>
          </span>
                </button>
                <div class="dropdown-menu dropdown-menu--sm p-0 border-0 box--shadow1 dropdown-menu-right">
                    <a href="{{ route('admin.profile') }}"
                       class="dropdown-menu__item d-flex align-items-center px-3 py-2">
                        <i class="dropdown-menu__icon las la-user-circle"></i>
                        <span class="dropdown-menu__caption">@lang('Perfil')</span>
                    </a>

                    <!-- <a href="{{route('admin.password')}}"
                       class="dropdown-menu__item d-flex align-items-center px-3 py-2">
                        <i class="dropdown-menu__icon las la-key"></i>
                        <span class="dropdown-menu__caption">@lang('Contraseña')</span>
                    </a> -->

                    <a href="{{ route('admin.logout') }}"
                       class="dropdown-menu__item d-flex align-items-center px-3 py-2">
                        <i class="dropdown-menu__icon las la-sign-out-alt"></i>
                        <span class="dropdown-menu__caption">@lang('Salir')</span>
                    </a>
                </div>
            </li>
        </ul>
    </div>
</nav>
<!-- navbar-wrapper end -->